//! Oracle conformance harness (port plan Task 12; spec §13 test corpus +
//! option matrix, §16 acceptance gates).
//!
//! Four layers, in order of strictness:
//!
//! 1. **Golden byte-compare** (runs everywhere): the Rust `jdiff` output must
//!    be byte-identical to the committed goldens under
//!    `tests/fixtures/golden/<pair>/<optset>.*`, which were generated by the
//!    C++ reference oracle via `scripts/gen-golden.sh` (canonical build:
//!    default `make` + spec §15.1 ifstream fix + §15.12 32-bit `hkey`).
//!    Verbose stderr captures for the text pair are compared as well.
//! 2. **Live-oracle byte-compare** (auto-skips): when the compiled C++
//!    reference is present (`$JOJODIFF_ORACLE`, else `target/oracle`), the
//!    Rust and C++ binaries are compared directly across the whole §13
//!    matrix — `jdiff` outputs and verbose stderr, and `jptch` outputs for
//!    every golden patch — and the live oracle output is itself checked
//!    against the committed goldens. Dormant since the 0.8.5 re-target
//!    (Task 13): the 0.8.5 oracle (`scripts/build-oracle.sh`, no jptch
//!    binary) emits different patch bytes and verbose text than the 0.8.1
//!    goldens, so the layer-2 tests are `#[ignore]`d TODO(T22) until Task 22
//!    re-pins them.
//! 3. **Round-trip gate** (runs everywhere, spec §16.1): `jdiff A B p &&
//!    jptch A p out` restores B byte-exact. In-memory mode (`-m 0`, `-m 1`)
//!    is included on the NUL pair here: the Rust in-memory reader serves
//!    full content (spec §15.3), so NUL inputs are verified by round-trip.
//! 4. **francisdb cross-validation** (runs everywhere, spec §16.4): the
//!    third-party `jojodiff` crate applies the Rust-produced patches of the
//!    NUL-free text pair, guarding against accidental format drift beyond
//!    the C++ oracle.
//!
//! The bundled corpus (`bkocomu.0000.fil`/`bkocomu.0009.fil`, ~1.8 MB binary
//! with NULs; `test2.001.txt`/`test2.002.txt`, CRLF text) is vendored
//! byte-exact from the C++ repo's `tests/` directory. Both pairs differ, so
//! every `jdiff` run below must exit 0 (differences found); the
//! identical-files exit-1 case is pinned in `tests/roundtrip.rs`.
//!
//! Unopenable-input cases are deliberately absent here: the stock Linux
//! oracle aborts on them (spec §15.11), so they are not oracle-comparable;
//! their documented exit codes and messages are pinned in
//! `tests/roundtrip.rs`.

use std::ffi::{OsStr, OsString};
use std::fs;
use std::io::Cursor;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicU32, Ordering};

/// The two bundled corpus pairs: (golden directory name, original, new).
const PAIRS: &[(&str, &str, &str)] = &[
    ("bkocomu", "bkocomu.0000.fil", "bkocomu.0009.fil"),
    ("test2", "test2.001.txt", "test2.002.txt"),
];

/// Option matrix of spec §13, applied to both pairs: (name, jdiff arguments,
/// output-file extension). `-l`/`-lr` produce listings (`.asc`/`.rgn`), the
/// rest produce binary patches (`.jdf`).
const OPTION_SETS: &[(&str, &[&str], &str)] = &[
    ("default", &[], "jdf"),
    ("f", &["-f"], "jdf"),
    ("ff", &["-ff"], "jdf"),
    ("b", &["-b"], "jdf"),
    ("s1", &["-s", "1"], "jdf"),
    ("s32", &["-s", "32"], "jdf"),
    ("bs512", &["-bs", "512"], "jdf"),
    ("m64", &["-m", "64"], "jdf"),
    ("min1max1", &["-min", "1", "-max", "1"], "jdf"),
    ("a16", &["-a", "16"], "jdf"),
    ("l", &["-l"], "asc"),
    ("lr", &["-lr"], "rgn"),
];

/// In-memory mode (`-m 0`, and `-m 1` which parses to buffer size 0) is
/// byte-compared against the oracle on the NUL-free text pair only: the C++
/// in-memory reader truncates at NUL bytes (spec §15.3), so on the NUL pair
/// it reports the files identical. The Rust in-memory reader serves full
/// content, so the NUL pair is verified by round-trip (layer 3) instead.
const IN_MEMORY_TEXT_ONLY: &[(&str, &[&str], &str)] =
    &[("m0", &["-m", "0"], "jdf"), ("m1", &["-m", "1"], "jdf")];

/// Verbose stderr captures generated for the text pair:
/// `<optset>.v.stderr` and `<optset>.vv.stderr` (greeting, progress and
/// statistics are deterministic; the oracle prints them to stddbg = stderr).
const VERBOSE_LEVELS: &[(&str, &str)] = &[("v", "-v"), ("vv", "-vv")];

/// Full live-oracle/golden matrix for a pair (the §13 sets plus in-memory
/// mode on the text pair). `-l`/`-lr` produce listings (`.asc`/`.rgn`), the
/// rest produce binary patches (`.jdf`).
fn option_sets_for(pair: &str) -> Vec<(&'static str, &'static [&'static str], &'static str)> {
    let mut sets: Vec<_> = OPTION_SETS.to_vec();
    if pair == "test2" {
        sets.extend(IN_MEMORY_TEXT_ONLY);
    }
    sets
}

/// The matrix entries with a committed golden. `bkocomu/l` is excluded by
/// design: its ASCII listing is ~80 MB and is verified by the live-oracle
/// layer instead (which the CI oracle job runs); `-l` on the text pair is
/// committed and covers the JOutAsc byte format in the always-run layer.
///
/// `f` is excluded since the Task 14 file-layer rewrite (spec §18.E): with
/// `-f` (out-of-buffer compare disabled) the engine's soft-ahead reads reach
/// a full buffer at 0.8.5 (`JFileAhead.cpp:303-304`) instead of one block at
/// 0.8.1, so the 0.8.1 engine lands on different match decisions — the
/// shipped 0.8.5 oracle itself no longer reproduces the 0.8.1 `f` golden.
/// TODO(T17/T22): byte parity for `-f` returns with the 0.8.5 engine port
/// and the 0.8.5-oracle re-pinned goldens.
fn committed_golden_sets(pair: &str) -> Vec<(&'static str, &'static [&'static str], &'static str)> {
    option_sets_for(pair)
        .into_iter()
        .filter(|&(name, _, _)| !(pair == "bkocomu" && name == "l"))
        .filter(|&(name, _, _)| name != "f")
        .collect()
}

/// Option sets that produce an appliable binary patch (no `-l`/`-lr`).
fn patch_sets_for(pair: &str) -> Vec<(&'static str, &'static [&'static str], &'static str)> {
    option_sets_for(pair)
        .into_iter()
        .filter(|&(_, _, ext)| ext == "jdf")
        .collect()
}

/// Option sets for the Rust-only round-trip gate: every patch-producing set,
/// plus in-memory mode on BOTH pairs — the Rust reader serves full content
/// (spec §15.3), so the NUL pair is verified by round-trip.
fn roundtrip_sets(pair: &str) -> Vec<(&'static str, &'static [&'static str], &'static str)> {
    let mut sets = patch_sets_for(pair);
    if pair == "bkocomu" {
        sets.extend(IN_MEMORY_TEXT_ONLY);
    }
    sets
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
}

fn golden_dir() -> PathBuf {
    fixtures_dir().join("golden")
}

fn fixture(file: &str) -> PathBuf {
    fixtures_dir().join(file)
}

/// Directory holding the compiled C++ reference (`jdiff` + `jptch`), or None.
/// Honours `$JOJODIFF_ORACLE`, else falls back to `target/oracle` as created
/// by `scripts/build-oracle.sh`.
fn oracle_dir() -> Option<PathBuf> {
    // Relative $JOJODIFF_ORACLE values must be made absolute: the tests spawn
    // the oracle binaries with `current_dir` set to a temp directory, which
    // would otherwise resolve the path against that directory.
    fn find(dir: &Path) -> Option<PathBuf> {
        if dir.join("jdiff").is_file() && dir.join("jptch").is_file() {
            dir.canonicalize().ok()
        } else {
            None
        }
    }
    if let Some(dir) = std::env::var_os("JOJODIFF_ORACLE") {
        return find(&PathBuf::from(dir));
    }
    find(
        &PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("target")
            .join("oracle"),
    )
}

/// Unique temp directory per test (parallel-safe), cleaned up by the caller.
fn temp_dir(tag: &str) -> PathBuf {
    static N: AtomicU32 = AtomicU32::new(0);
    let dir = std::env::temp_dir().join(format!(
        "jdiff-t12-{}-{}-{}",
        tag,
        std::process::id(),
        N.fetch_add(1, Ordering::Relaxed)
    ));
    fs::create_dir_all(&dir).expect("create temp dir");
    dir
}

/// Run a binary with OsString `args` inside `dir`.
fn run_in(dir: &Path, exe: &Path, args: &[OsString]) -> Output {
    Command::new(exe)
        .args(args)
        .current_dir(dir)
        .output()
        .unwrap_or_else(|e| panic!("spawn {}: {e}", exe.display()))
}

/// jdiff argument vector for an option set: `[opts…] org new out` (absolute
/// fixture paths, output file last) so Rust and C++ runs are comparable.
fn jdiff_args(opts: &[&str], org: &Path, new: &Path, out: &Path) -> Vec<OsString> {
    let mut args: Vec<OsString> = opts.iter().map(|o| OsStr::new(o).to_os_string()).collect();
    args.push(org.as_os_str().to_os_string());
    args.push(new.as_os_str().to_os_string());
    args.push(out.as_os_str().to_os_string());
    args
}

fn jptch_args(org: &Path, patch: &Path, out: &Path) -> Vec<OsString> {
    vec![
        org.as_os_str().to_os_string(),
        patch.as_os_str().to_os_string(),
        out.as_os_str().to_os_string(),
    ]
}

fn assert_exit0(out: &Output, what: &str) {
    assert!(
        out.status.success(),
        "{what} exited with code {:?}\nstderr:\n{}",
        out.status.code(),
        String::from_utf8_lossy(&out.stderr)
    );
}

// ---------------------------------------------------------------------------
// Layer 1: golden byte-compare (runs everywhere; goldens are committed)
// ---------------------------------------------------------------------------

/// Rust `jdiff` output must equal every committed golden byte-for-byte
/// (patch, ASCII listing or region listing) and exit 0 (both pairs differ).
/// `bkocomu/l` has no committed golden by design (~80 MB listing; verified
/// live against the oracle by `live_oracle_jdiff_matches`).
#[test]
fn golden_jdiff_outputs_match() {
    assert!(
        golden_dir().is_dir(),
        "committed goldens missing at {} - run scripts/gen-golden.sh (goldens are\n\
         generated by the C++ oracle, never from Rust output)",
        golden_dir().display()
    );
    for (pair, org, new) in PAIRS {
        for (name, opts, ext) in committed_golden_sets(pair) {
            let golden = golden_dir().join(pair).join(format!("{name}.{ext}"));
            let golden_bytes = fs::read(&golden)
                .unwrap_or_else(|e| panic!("read golden {}: {e}", golden.display()));
            let dir = temp_dir(&format!("golden-{pair}-{name}"));
            let out = dir.join("output.bin");
            let outp = run_in(
                &dir,
                Path::new(env!("CARGO_BIN_EXE_jdiff")),
                &jdiff_args(opts, &fixture(org), &fixture(new), &out),
            );
            assert_exit0(&outp, &format!("rust jdiff {pair}/{name}"));
            assert!(
                outp.stdout.is_empty(),
                "rust jdiff {pair}/{name}: stdout must stay empty (output goes to the file)"
            );
            let rust_bytes = fs::read(&out).expect("rust jdiff output");
            assert_eq!(
                rust_bytes, golden_bytes,
                "rust jdiff output diverges from oracle golden for {pair}/{name}"
            );
            fs::remove_dir_all(&dir).expect("clean temp dir");
        }
    }
}

/// Rust `jdiff` verbose stderr must equal the committed `-v`/`-vv` captures
/// of the oracle for the text pair (greeting, progress and statistics).
// TODO(T20): the captures embed the byte-exact 0.8.1 greeting; Task 13
// re-pointed JDIFF_VERSION/JDIFF_COPYRIGHT to the 0.8.5 strings and Task 20
// rewrites the banner text (the goldens are re-pinned by the 0.8.5 oracle
// work, Task 22).
#[ignore]
#[test]
fn golden_verbose_stderr_matches() {
    let (pair, org, new) = PAIRS[1]; // text pair
    for (name, opts) in patch_sets_for(pair).into_iter().map(|(n, o, _)| (n, o)) {
        for (vtag, vopt) in VERBOSE_LEVELS {
            let golden = golden_dir()
                .join(pair)
                .join(format!("{name}.{vtag}.stderr"));
            let golden_bytes = fs::read(&golden)
                .unwrap_or_else(|e| panic!("read golden {}: {e}", golden.display()));
            let dir = temp_dir(&format!("gverb-{pair}-{name}-{vtag}"));
            let out = dir.join("output.bin");
            let mut all: Vec<&str> = vec![vopt];
            all.extend_from_slice(opts);
            let outp = run_in(
                &dir,
                Path::new(env!("CARGO_BIN_EXE_jdiff")),
                &jdiff_args(&all, &fixture(org), &fixture(new), &out),
            );
            assert_exit0(&outp, &format!("rust jdiff -{vtag} {pair}/{name}"));
            assert!(
                outp.stdout.is_empty(),
                "verbose output goes to stderr by default ({pair}/{name} -{vtag})"
            );
            assert_eq!(
                outp.stderr, golden_bytes,
                "rust jdiff verbose stderr diverges from oracle golden for {pair}/{name} -{vtag}"
            );
            fs::remove_dir_all(&dir).expect("clean temp dir");
        }
    }
}

// ---------------------------------------------------------------------------
// Layer 2: live-oracle byte-compare (auto-skips without the oracle)
// ---------------------------------------------------------------------------

fn skip_message() -> &'static str {
    "skipping: no oracle ($JOJODIFF_ORACLE unset and target/oracle missing)"
}

/// Direct Rust-vs-C++ comparison of `jdiff` across the whole §13 matrix, plus
/// a re-validation of the committed goldens against the live oracle.
// TODO(T22): the 0.8.5 oracle emits different patch bytes than the committed
// 0.8.1 goldens (implicit MOD, MINEQL=2), so neither half of this test can
// pass until Task 22 re-pins the oracle layer; the Rust-vs-golden layer 1
// above stays active and keeps passing.
#[ignore]
#[test]
fn live_oracle_jdiff_matches() {
    let Some(oracle) = oracle_dir() else {
        eprintln!("{}", skip_message());
        return;
    };
    let oracle_jdiff = oracle.join("jdiff");
    for (pair, org, new) in PAIRS {
        for (name, opts, ext) in option_sets_for(pair) {
            let golden = golden_dir().join(pair).join(format!("{name}.{ext}"));
            let golden_bytes = if golden.is_file() {
                Some(fs::read(&golden).expect("committed golden"))
            } else {
                // Only bkocomu/l has no committed golden (~80 MB); the live
                // Rust-vs-C++ comparison below is the verification for it.
                assert!(
                    *pair == "bkocomu" && name == "l",
                    "committed golden missing: {}",
                    golden.display()
                );
                None
            };
            let mut runs: Vec<(PathBuf, Output, PathBuf)> = Vec::new(); // (dir, output, out-file)
            for (tag, exe) in [
                ("cpp", oracle_jdiff.as_path()),
                ("rs", Path::new(env!("CARGO_BIN_EXE_jdiff"))),
            ] {
                let dir = temp_dir(&format!("live-{pair}-{name}-{tag}"));
                let out_file = dir.join("output.bin");
                let outp = run_in(
                    &dir,
                    exe,
                    &jdiff_args(opts, &fixture(org), &fixture(new), &out_file),
                );
                assert_exit0(&outp, &format!("{tag} jdiff {pair}/{name}"));
                assert!(
                    outp.stdout.is_empty(),
                    "{tag} jdiff {pair}/{name}: stdout must stay empty"
                );
                runs.push((dir, outp, out_file));
            }
            let (dir_cpp, outp_cpp, file_cpp) = runs.remove(0);
            let (dir_rs, outp_rs, file_rs) = runs.remove(0);
            let cpp_bytes = fs::read(&file_cpp).expect("cpp output");
            let rs_bytes = fs::read(&file_rs).expect("rs output");
            assert_eq!(
                rs_bytes, cpp_bytes,
                "Rust and C++ jdiff diverge for {pair}/{name}"
            );
            if let Some(golden_bytes) = golden_bytes {
                assert_eq!(
                    rs_bytes, golden_bytes,
                    "live oracle output no longer matches committed golden for {pair}/{name}"
                );
            }
            assert_eq!(outp_rs.status.code(), outp_cpp.status.code());
            fs::remove_dir_all(&dir_cpp).expect("clean temp dir");
            fs::remove_dir_all(&dir_rs).expect("clean temp dir");
        }
    }
}

/// Live Rust-vs-C++ comparison of `jdiff` verbose stderr on the text pair.
// TODO(T22): the 0.8.5 oracle verbose output (banner, statistics) differs
// from the committed 0.8.1 captures; re-pinned by Task 22.
#[ignore]
#[test]
fn live_oracle_verbose_stderr_matches() {
    let Some(oracle) = oracle_dir() else {
        eprintln!("{}", skip_message());
        return;
    };
    let (pair, org, new) = PAIRS[1]; // text pair
    for (name, opts) in patch_sets_for(pair).into_iter().map(|(n, o, _)| (n, o)) {
        for (vtag, vopt) in VERBOSE_LEVELS {
            let golden_bytes = fs::read(
                golden_dir()
                    .join(pair)
                    .join(format!("{name}.{vtag}.stderr")),
            )
            .expect("committed verbose golden");
            let mut runs: Vec<(PathBuf, Output)> = Vec::new();
            for (tag, exe) in [
                ("cpp", oracle.join("jdiff")),
                ("rs", PathBuf::from(env!("CARGO_BIN_EXE_jdiff"))),
            ] {
                let dir = temp_dir(&format!("lverb-{pair}-{name}-{vtag}-{tag}"));
                let out_file = dir.join("output.bin");
                let mut all: Vec<&str> = vec![vopt];
                all.extend_from_slice(opts);
                let outp = run_in(
                    &dir,
                    &exe,
                    &jdiff_args(&all, &fixture(org), &fixture(new), &out_file),
                );
                assert_exit0(&outp, &format!("{tag} jdiff -{vtag} {pair}/{name}"));
                runs.push((dir, outp));
            }
            let (dir_cpp, outp_cpp) = runs.remove(0);
            let (dir_rs, outp_rs) = runs.remove(0);
            assert_eq!(
                outp_rs.stderr, outp_cpp.stderr,
                "Rust and C++ jdiff verbose stderr diverge for {pair}/{name} -{vtag}"
            );
            assert_eq!(
                outp_rs.stderr, golden_bytes,
                "live oracle stderr no longer matches committed golden for {pair}/{name} -{vtag}"
            );
            fs::remove_dir_all(&dir_cpp).expect("clean temp dir");
            fs::remove_dir_all(&dir_rs).expect("clean temp dir");
        }
    }
}

/// Apply every golden patch with both `jptch` binaries: outputs must be
/// byte-identical to each other and to the new file (which also re-proves
/// the golden patch itself).
// TODO(T22): 0.8.5 ships no jptch binary (patching is `jdiff -u`/argv[0]),
// so the oracle half of this test is impossible until Task 22 rebuilds the
// patching leg of the harness (the 0.8.5 tree has no jptch either; see
// scripts/build-oracle-081.sh for the legacy 0.8.1 oracle with jptch).
#[ignore]
#[test]
fn live_oracle_jptch_matches() {
    let Some(oracle) = oracle_dir() else {
        eprintln!("{}", skip_message());
        return;
    };
    let oracle_jptch = oracle.join("jptch");
    for (pair, org, new) in PAIRS {
        for (name, _, _) in patch_sets_for(pair) {
            let patch = golden_dir().join(pair).join(format!("{name}.jdf"));
            assert!(
                patch.is_file(),
                "committed golden patch missing: {}",
                patch.display()
            );
            let new_bytes = fs::read(fixture(new)).expect("read new file");
            let mut runs: Vec<(PathBuf, Output, PathBuf)> = Vec::new();
            for (tag, exe) in [
                ("cpp", oracle_jptch.as_path()),
                ("rs", Path::new(env!("CARGO_BIN_EXE_jptch"))),
            ] {
                let dir = temp_dir(&format!("lptch-{pair}-{name}-{tag}"));
                let out_file = dir.join("patched.bin");
                let outp = run_in(&dir, exe, &jptch_args(&fixture(org), &patch, &out_file));
                assert_exit0(&outp, &format!("{tag} jptch {pair}/{name}"));
                runs.push((dir, outp, out_file));
            }
            let (dir_cpp, outp_cpp, file_cpp) = runs.remove(0);
            let (dir_rs, outp_rs, file_rs) = runs.remove(0);
            let cpp_bytes = fs::read(&file_cpp).expect("cpp jptch output");
            let rs_bytes = fs::read(&file_rs).expect("rs jptch output");
            assert_eq!(
                rs_bytes, cpp_bytes,
                "Rust and C++ jptch diverge for golden patch {pair}/{name}"
            );
            assert_eq!(outp_rs.status.code(), outp_cpp.status.code());
            assert_eq!(
                rs_bytes, new_bytes,
                "patched output != new file ({pair}/{name})"
            );
            fs::remove_dir_all(&dir_cpp).expect("clean temp dir");
            fs::remove_dir_all(&dir_rs).expect("clean temp dir");
        }
    }
}

// ---------------------------------------------------------------------------
// Layer 3: round-trip gate (runs everywhere, spec §16.1)
// ---------------------------------------------------------------------------

/// `jdiff A B p && jptch A p out` restores B byte-exact for every pair ×
/// patch-producing option set. Includes in-memory mode on BOTH pairs: the
/// Rust reader serves full content (spec §15.3), so the NUL pair — not
/// oracle-comparable in that mode — is verified by round-trip.
#[test]
fn roundtrip_gate() {
    for (pair, org, new) in PAIRS {
        let new_bytes = fs::read(fixture(new)).expect("read new file");
        for (name, opts, _) in roundtrip_sets(pair) {
            let dir = temp_dir(&format!("rt-{pair}-{name}"));
            let patch = dir.join("patch.jdf");
            let patched = dir.join("patched.bin");
            let d = run_in(
                &dir,
                Path::new(env!("CARGO_BIN_EXE_jdiff")),
                &jdiff_args(opts, &fixture(org), &fixture(new), &patch),
            );
            assert_exit0(&d, &format!("jdiff {pair}/{name}"));
            assert!(
                fs::metadata(&patch).expect("patch file").len() > 0,
                "jdiff {pair}/{name}: patch for a differing pair must not be empty"
            );
            let p = run_in(
                &dir,
                Path::new(env!("CARGO_BIN_EXE_jptch")),
                &jptch_args(&fixture(org), &patch, &patched),
            );
            assert_exit0(&p, &format!("jptch {pair}/{name}"));
            assert_eq!(
                fs::read(&patched).expect("patched output"),
                new_bytes,
                "round-trip failed for {pair}/{name}"
            );
            fs::remove_dir_all(&dir).expect("clean temp dir");
        }
    }
}

// ---------------------------------------------------------------------------
// Layer 4: francisdb cross-validation (runs everywhere, spec §16.4)
// ---------------------------------------------------------------------------

/// The third-party `jojodiff` crate (v0.1.2) applies the Rust-produced
/// patches of the NUL-free text pair. Its `patch` signature takes both
/// readers as the same concrete type (`patch<R: Read + Seek, W: Write>(
/// in_reader: &mut R, patch_reader: &mut R, out_writer: &mut W)`), so
/// `Cursor<Vec<u8>>` is used for both.
#[test]
fn francisdb_cross_validation() {
    let (pair, org, new) = PAIRS[1]; // text pair, NUL-free (spec §16.4)
    let org_bytes = fs::read(fixture(org)).expect("read original file");
    let new_bytes = fs::read(fixture(new)).expect("read new file");
    for (name, opts, _) in patch_sets_for(pair) {
        let dir = temp_dir(&format!("fdb-{pair}-{name}"));
        let patch = dir.join("patch.jdf");
        let d = run_in(
            &dir,
            Path::new(env!("CARGO_BIN_EXE_jdiff")),
            &jdiff_args(opts, &fixture(org), &fixture(new), &patch),
        );
        assert_exit0(&d, &format!("jdiff {pair}/{name}"));
        let patch_bytes = fs::read(&patch).expect("read patch");

        let mut org_reader = Cursor::new(org_bytes.clone());
        let mut patch_reader = Cursor::new(patch_bytes);
        let mut out: Vec<u8> = Vec::new();
        jojodiff::patch(&mut org_reader, &mut patch_reader, &mut out)
            .expect("francisdb jojodiff::patch");
        assert_eq!(
            out, new_bytes,
            "francisdb-applied patch differs for {pair}/{name}"
        );
        fs::remove_dir_all(&dir).expect("clean temp dir");
    }
}
