//! Oracle conformance harness (spec §13 test corpus + §22 acceptance gates;
//! port plan Task 12, re-pointed to the 0.8.5 oracle in Task 20).
//!
//! Four layers, in order of strictness:
//!
//! 1. **Golden byte-compare** (runs everywhere): the Rust `jdiff` output must
//!    be byte-identical to the committed goldens under
//!    `tests/fixtures/golden/<pair>/<optset>.*`. TODO(T22): the committed
//!    goldens were generated by the 0.8.1 oracle and no longer match the
//!    0.8.5 engine/writer (implicit MOD, MINEQL=2, new match decisions);
//!    Task 22 regenerates them from the 0.8.5 oracle — until then this layer
//!    compares nothing (the goldens-directory existence check stays; the
//!    0.8.1 goldens are never touched).
//! 2. **Live-oracle byte-compare** (auto-skips): when the compiled C++ 0.8.5
//!    reference is present (`$JOJODIFF_ORACLE`, else `target/oracle/jdiff`
//!    from `scripts/build-oracle.sh`), the Rust and C++ binaries are compared
//!    directly: patch bytes and `-l`/`-r` listings across the §22.1 matrix on
//!    the tiny pair, verbose stderr with the two documented port deviations
//!    masked, cross-applied patches (`jdiff -u` on both sides), and the
//!    index-table element-count equivalence (`-i 8` port ≡ `-i 6` oracle,
//!    spec §18.E/§21.7: the port's fixed 16-byte element divisor vs the
//!    32-bit-hkey oracle's 12).
//! 3. **Round-trip gate** (runs everywhere, spec §22.1): `jdiff OPTS A B p &&
//!    jdiff -u A p out` restores B byte-exact across the whole matrix (one
//!    binary; argv[0] equivalents are covered in tests/roundtrip.rs).
//! 4. **francisdb cross-validation** (runs everywhere, spec §16.4): the
//!    third-party `jojodiff` crate applies the Rust-produced patches of the
//!    NUL-free text pair (its reader defaults the operator to MOD — the
//!    0.8.5 reader semantics — so implicit-MOD patches apply).
//!
//! The bundled corpus (`bkocomu.0000.fil`/`bkocomu.0009.fil`, ~1.8 MB binary
//! with NULs; `test2.001.txt`/`test2.002.txt`, CRLF text) is vendored
//! byte-exact from the C++ repo's `tests/` directory. Both pairs differ, so
//! every `jdiff` run below must exit 1 (differences found — 0.8.5 swapped the
//! exit codes); the identical-files exit-0 case is pinned in
//! `tests/roundtrip.rs`.

use std::ffi::{OsStr, OsString};
use std::fs;
use std::io::Cursor;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicU32, Ordering};

/// The two bundled corpus pairs: (golden directory name, original, new).
const PAIRS: &[(&str, &str, &str)] = &[
    ("bkocomu", "bkocomu.0000.fil", "bkocomu.0009.fil"),
    ("test2", "test2.001.txt", "test2.002.txt"),
];

/// Option matrix of spec §22.1 (0.8.5 CLI), applied to both pairs:
/// (name, jdiff arguments, output-file extension). `-l`/`-r` produce listings
/// (`.asc`/`.rgn`), the rest produce binary patches (`.jdf`).
const OPTION_SETS: &[(&str, &[&str], &str)] = &[
    ("default", &[], "jdf"),
    ("b", &["-b"], "jdf"),
    ("bb", &["-bb"], "jdf"),
    ("f", &["-f"], "jdf"),
    ("ff", &["-ff"], "jdf"),
    ("p", &["-p"], "jdf"),
    ("q", &["-q"], "jdf"),
    ("pq", &["-p", "-q"], "jdf"),
    ("s", &["-s"], "jdf"),
    ("i1", &["-i", "1"], "jdf"),
    ("i8", &["-i", "8"], "jdf"),
    ("i512", &["-i", "512"], "jdf"),
    ("k0", &["-k", "0"], "jdf"),
    ("k1", &["-k", "1"], "jdf"),
    ("k65565", &["-k", "65565"], "jdf"),
    ("n1x2", &["-n", "1", "-x", "2"], "jdf"),
    ("x5", &["-x", "5"], "jdf"),
    ("m0", &["-m", "0"], "jdf"),
    ("m7", &["-m", "7"], "jdf"),
    ("m2048", &["-m", "2048"], "jdf"),
    ("a0", &["-a", "0"], "jdf"),
    ("a1", &["-a", "1"], "jdf"),
    ("l", &["-l"], "asc"),
    ("r", &["-r"], "rgn"),
];

/// Verbose stderr captures compared live against the oracle on the tiny pair.
const VERBOSE_LEVELS: &[(&str, &str)] = &[("v", "-v"), ("vv", "-vv")];

/// Tiny fixture pair (as in tests/roundtrip.rs) for the byte-exact live
/// comparisons: small enough that both engines land on identical match
/// decisions at every option set despite the documented index-divisor
/// deviation (§18.E).
const TINY_ORG: &[u8] = b"hello world hello";
const TINY_NEW: &[u8] = b"hello world byebye";

/// The matrix entries that produce an appliable binary patch (no `-l`/`-r`).
fn patch_sets() -> Vec<(&'static str, &'static [&'static str], &'static str)> {
    OPTION_SETS
        .iter()
        .filter(|&(_, _, ext)| *ext == "jdf")
        .copied()
        .collect()
}

/// Option sets for the round-trip gate: every patch-producing set (the two
/// listing sets round-trip a default patch in tests/roundtrip.rs already).
fn roundtrip_sets(pair: &str) -> Vec<(&'static str, &'static [&'static str])> {
    let _ = pair;
    patch_sets().into_iter().map(|(n, o, _)| (n, o)).collect()
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
}

fn golden_dir() -> PathBuf {
    fixtures_dir().join("golden")
}

fn fixture(file: &str) -> PathBuf {
    fixtures_dir().join(file)
}

/// Directory holding the compiled C++ 0.8.5 reference (`jdiff` — 0.8.5 ships
/// a single binary, spec §18.B), or None. Honours `$JOJODIFF_ORACLE`, else
/// falls back to `target/oracle` as created by `scripts/build-oracle.sh`.
fn oracle_dir() -> Option<PathBuf> {
    // Relative $JOJODIFF_ORACLE values must be made absolute: the tests spawn
    // the oracle binaries with `current_dir` set to a temp directory, which
    // would otherwise resolve the path against that directory.
    fn find(dir: &Path) -> Option<PathBuf> {
        if dir.join("jdiff").is_file() {
            dir.canonicalize().ok()
        } else {
            None
        }
    }
    if let Some(dir) = std::env::var_os("JOJODIFF_ORACLE") {
        return find(&PathBuf::from(dir));
    }
    find(
        &PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("target")
            .join("oracle"),
    )
}

/// Unique temp directory per test (parallel-safe), cleaned up by the caller.
fn temp_dir(tag: &str) -> PathBuf {
    static N: AtomicU32 = AtomicU32::new(0);
    let dir = std::env::temp_dir().join(format!(
        "jdiff-t12-{}-{}-{}",
        tag,
        std::process::id(),
        N.fetch_add(1, Ordering::Relaxed)
    ));
    fs::create_dir_all(&dir).expect("create temp dir");
    dir
}

/// Run a binary with OsString `args` inside `dir`.
fn run_in(dir: &Path, exe: &Path, args: &[OsString]) -> Output {
    Command::new(exe)
        .args(args)
        .current_dir(dir)
        .output()
        .unwrap_or_else(|e| panic!("spawn {}: {e}", exe.display()))
}

/// jdiff argument vector for an option set: `[opts…] org new out` (absolute
/// fixture paths, output file last) so Rust and C++ runs are comparable.
fn jdiff_args(opts: &[&str], org: &Path, new: &Path, out: &Path) -> Vec<OsString> {
    let mut args: Vec<OsString> = opts.iter().map(|o| OsStr::new(o).to_os_string()).collect();
    args.push(org.as_os_str().to_os_string());
    args.push(new.as_os_str().to_os_string());
    args.push(out.as_os_str().to_os_string());
    args
}

fn apply_args(org: &Path, patch: &Path, out: &Path) -> Vec<OsString> {
    let mut args: Vec<OsString> = vec![OsStr::new("-u").to_os_string()];
    args.push(org.as_os_str().to_os_string());
    args.push(patch.as_os_str().to_os_string());
    args.push(out.as_os_str().to_os_string());
    args
}

fn assert_exit0(out: &Output, what: &str) {
    assert!(
        out.status.success(),
        "{what} exited with code {:?}\nstderr:\n{}",
        out.status.code(),
        String::from_utf8_lossy(&out.stderr)
    );
}

/// Asserts a differing-pair jdiff run exited 1 (0.8.5 exit swap).
fn assert_exit1(out: &Output, what: &str) {
    assert_eq!(
        out.status.code(),
        Some(1),
        "{what} exited with code {:?}\nstderr:\n{}",
        out.status.code(),
        String::from_utf8_lossy(&out.stderr)
    );
}

// ---------------------------------------------------------------------------
// Layer 1: golden byte-compare (runs everywhere; goldens are committed)
// ---------------------------------------------------------------------------

/// The committed goldens are 0.8.1-oracle captures; they stopped matching the
/// port at the 0.8.5 re-target (engine Tasks 15-17, writer Task 18, CLI
/// Task 20 — every option set diverged by now). Task 22 regenerates the
/// goldens from the 0.8.5 oracle; until then the layer-1 byte-compare
/// compares nothing and only the goldens-directory existence is checked (the
/// 0.8.1 goldens are never touched — they re-pin the cross-version gate).
fn committed_golden_sets(_pair: &str) -> Vec<(&'static str, &'static [&'static str], &'static str)>
{
    Vec::new()
}

/// The goldens directory must exist (its files re-pin the cross-version
/// compatibility gate, spec §22.3, and are regenerated from the 0.8.5 oracle
/// in Task 22).
#[test]
fn golden_jdiff_outputs_match() {
    assert!(
        golden_dir().is_dir(),
        "committed goldens missing at {} - run scripts/gen-golden.sh (goldens are\n\
         generated by the C++ oracle, never from Rust output)",
        golden_dir().display()
    );
    for (pair, org, new) in PAIRS {
        for (name, opts, ext) in committed_golden_sets(pair) {
            let golden = golden_dir().join(pair).join(format!("{name}.{ext}"));
            let golden_bytes = fs::read(&golden)
                .unwrap_or_else(|e| panic!("read golden {}: {e}", golden.display()));
            let dir = temp_dir(&format!("golden-{pair}-{name}"));
            let out = dir.join("output.bin");
            let outp = run_in(
                &dir,
                Path::new(env!("CARGO_BIN_EXE_jdiff")),
                &jdiff_args(opts, &fixture(org), &fixture(new), &out),
            );
            assert_exit1(&outp, &format!("rust jdiff {pair}/{name}"));
            assert!(
                outp.stdout.is_empty(),
                "rust jdiff {pair}/{name}: stdout must stay empty (output goes to the file)"
            );
            let rust_bytes = fs::read(&out).expect("rust jdiff output");
            assert_eq!(
                rust_bytes, golden_bytes,
                "rust jdiff output diverges from oracle golden for {pair}/{name}"
            );
            fs::remove_dir_all(&dir).expect("clean temp dir");
        }
    }
}

/// Rust `jdiff` verbose stderr must equal the committed `-v`/`-vv` captures
/// of the oracle for the text pair (greeting, progress and statistics).
// TODO(T22): the committed captures embed the 0.8.1 greeting and 0.8.1
// statistics blocks; Task 20 re-pointed the live verbose comparison to the
// 0.8.5 oracle (see `live_oracle_verbose_stderr_matches`). Task 22 regenerates
// the captures from the 0.8.5 oracle and re-enables this layer-1 pin.
#[ignore]
#[test]
fn golden_verbose_stderr_matches() {
    let (pair, org, new) = PAIRS[1]; // text pair
    for (name, opts) in patch_sets().into_iter().map(|(n, o, _)| (n, o)) {
        for (vtag, vopt) in VERBOSE_LEVELS {
            let golden = golden_dir()
                .join(pair)
                .join(format!("{name}.{vtag}.stderr"));
            let golden_bytes = fs::read(&golden)
                .unwrap_or_else(|e| panic!("read golden {}: {e}", golden.display()));
            let dir = temp_dir(&format!("gverb-{pair}-{name}-{vtag}"));
            let out = dir.join("output.bin");
            let mut all: Vec<&str> = vec![vopt];
            all.extend_from_slice(opts);
            let outp = run_in(
                &dir,
                Path::new(env!("CARGO_BIN_EXE_jdiff")),
                &jdiff_args(&all, &fixture(org), &fixture(new), &out),
            );
            assert_exit1(&outp, &format!("rust jdiff -{vtag} {pair}/{name}"));
            assert!(
                outp.stdout.is_empty(),
                "verbose output goes to stderr by default ({pair}/{name} -{vtag})"
            );
            assert_eq!(
                outp.stderr, golden_bytes,
                "rust jdiff verbose stderr diverges from oracle golden for {pair}/{name} -{vtag}"
            );
            fs::remove_dir_all(&dir).expect("clean temp dir");
        }
    }
}

// ---------------------------------------------------------------------------
// Layer 2: live-oracle byte-compare (auto-skips without the 0.8.5 oracle)
// ---------------------------------------------------------------------------

fn skip_message() -> &'static str {
    "skipping: no 0.8.5 oracle ($JOJODIFF_ORACLE unset and target/oracle/jdiff missing)"
}

/// Masks for the two documented port-vs-oracle deviations in the verbose
/// stream (spec §18.E/§21.6), applied to both sides before comparing:
/// - the "Index table size" line prints each side's actual table (port /16:
///   `24Mb (2097143 samples)`; 32-bit-hkey oracle /12: `32Mb (2796181
///   samples)`);
/// - the "Inaccurate  solutions" line prints the C++ uninitialized counter
///   baseline on the oracle and the port's deterministic 0.
fn mask_deviation_lines(stderr: &str) -> String {
    stderr
        .lines()
        .map(|line| {
            if line.starts_with("Index table size") {
                "Index table size (masked)"
            } else if line.starts_with("Inaccurate  solutions") {
                "Inaccurate  solutions   (masked)"
            } else {
                line
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Direct Rust-vs-C++ 0.8.5 comparison across the §22.1 matrix:
/// - tiny pair: patch/listing bytes and exit codes byte-exact on every set;
/// - corpus pairs: exit-code parity and mutual round-trip (both patches
///   restore the new file through their own `-u`) — the index-divisor
///   deviation legitimately shifts match decisions on the repetitive 1.8 MB
///   pair, so patch bytes are compared only through the element-count
///   equivalence test below.
#[test]
fn live_oracle_jdiff_matches() {
    let Some(oracle) = oracle_dir() else {
        eprintln!("{}", skip_message());
        return;
    };
    let oracle_jdiff = oracle.join("jdiff");
    let rust_jdiff = PathBuf::from(env!("CARGO_BIN_EXE_jdiff"));

    // Tiny pair: write fixtures, byte-compare every set's output.
    let tdir = temp_dir("live-tiny");
    let org = tdir.join("a.bin");
    let new = tdir.join("b.bin");
    fs::write(&org, TINY_ORG).unwrap();
    fs::write(&new, TINY_NEW).unwrap();
    for (name, opts, _) in OPTION_SETS {
        let mut outs: Vec<(PathBuf, Output, PathBuf)> = Vec::new(); // (dir, output, out-file)
        for (tag, exe) in [("cpp", &oracle_jdiff), ("rs", &rust_jdiff)] {
            let dir = temp_dir(&format!("live-tiny-{name}-{tag}"));
            let out_file = dir.join("output.bin");
            let outp = run_in(
                &dir,
                exe,
                &jdiff_args(opts, &org, &new, &out_file),
            );
            assert_exit1(&outp, &format!("{tag} jdiff tiny/{name}"));
            assert!(
                outp.stdout.is_empty(),
                "{tag} jdiff tiny/{name}: stdout must stay empty"
            );
            outs.push((dir, outp, out_file));
        }
        let (dir_cpp, outp_cpp, file_cpp) = outs.remove(0);
        let (dir_rs, outp_rs, file_rs) = outs.remove(0);
        assert_eq!(
            fs::read(&file_rs).expect("rs output"),
            fs::read(&file_cpp).expect("cpp output"),
            "Rust and C++ jdiff diverge for tiny/{name}"
        );
        assert_eq!(outp_rs.status.code(), outp_cpp.status.code());
        fs::remove_dir_all(&dir_cpp).expect("clean temp dir");
        fs::remove_dir_all(&dir_rs).expect("clean temp dir");
    }
    fs::remove_dir_all(&tdir).expect("clean temp dir");

    // Corpus pairs: exit-code parity + mutual round-trip.
    for (pair, org, new) in PAIRS {
        let new_bytes = fs::read(fixture(new)).expect("read new file");
        for (name, opts, ext) in OPTION_SETS {
            if *ext != "jdf" {
                // Listings on the corpus pairs are compared by Task 22's
                // regenerated goldens; running 80 MB listings here would
                // dominate the suite.
                continue;
            }
            for (tag, exe) in [("cpp", &oracle_jdiff), ("rs", &rust_jdiff)] {
                let dir = temp_dir(&format!("live-{pair}-{name}-{tag}"));
                let patch = dir.join("patch.jdf");
                let restored = dir.join("restored.bin");
                let outp = run_in(
                    &dir,
                    exe,
                    &jdiff_args(opts, &fixture(org), &fixture(new), &patch),
                );
                assert_exit1(&outp, &format!("{tag} jdiff {pair}/{name}"));
                let outp = run_in(&dir, exe, &apply_args(&fixture(org), &patch, &restored));
                assert_exit0(&outp, &format!("{tag} -u {pair}/{name}"));
                assert_eq!(
                    fs::read(&restored).expect("restored"),
                    new_bytes,
                    "{tag} round-trip failed for {pair}/{name}"
                );
                fs::remove_dir_all(&dir).expect("clean temp dir");
            }
        }
    }
}

/// Live Rust-vs-C++ comparison of `jdiff` verbose stderr on the tiny pair,
/// byte-exact after masking the two documented deviations (index-table size
/// line, inaccurate-solutions baseline).
#[test]
fn live_oracle_verbose_stderr_matches() {
    let Some(oracle) = oracle_dir() else {
        eprintln!("{}", skip_message());
        return;
    };
    let tdir = temp_dir("lverb-tiny");
    let org = tdir.join("a.bin");
    let new = tdir.join("b.bin");
    fs::write(&org, TINY_ORG).unwrap();
    fs::write(&new, TINY_NEW).unwrap();
    for (vtag, vopt) in VERBOSE_LEVELS {
        let mut runs: Vec<(PathBuf, Output)> = Vec::new();
        for (tag, exe) in [
            ("cpp", oracle.join("jdiff")),
            ("rs", PathBuf::from(env!("CARGO_BIN_EXE_jdiff"))),
        ] {
            let dir = temp_dir(&format!("lverb-tiny-{vtag}-{tag}"));
            let out_file = dir.join("output.bin");
            let outp = run_in(
                &dir,
                &exe,
                &jdiff_args(&[vopt], &org, &new, &out_file),
            );
            assert_exit1(&outp, &format!("{tag} jdiff -{vtag} tiny"));
            runs.push((dir, outp));
        }
        let (dir_cpp, outp_cpp) = runs.remove(0);
        let (dir_rs, outp_rs) = runs.remove(0);
        assert_eq!(
            mask_deviation_lines(&String::from_utf8_lossy(&outp_rs.stderr)),
            mask_deviation_lines(&String::from_utf8_lossy(&outp_cpp.stderr)),
            "Rust and C++ jdiff verbose stderr diverge for tiny -{vtag}"
        );
        fs::remove_dir_all(&dir_cpp).expect("clean temp dir");
        fs::remove_dir_all(&dir_rs).expect("clean temp dir");
    }
    fs::remove_dir_all(&tdir).expect("clean temp dir");
}

/// Cross-applies patches through both binaries' `-u`: for the tiny pair,
/// every patch-producing matrix set must restore the new file when applied
/// by EITHER binary (0.8.5 reader ⇄ 0.8.5 writer, spec §18.C).
#[test]
fn live_oracle_patch_cross_applies() {
    let Some(oracle) = oracle_dir() else {
        eprintln!("{}", skip_message());
        return;
    };
    let oracle_jdiff = oracle.join("jdiff");
    let rust_jdiff = PathBuf::from(env!("CARGO_BIN_EXE_jdiff"));
    let tdir = temp_dir("cross-tiny");
    let org = tdir.join("a.bin");
    let new = tdir.join("b.bin");
    fs::write(&org, TINY_ORG).unwrap();
    fs::write(&new, TINY_NEW).unwrap();

    for (name, opts, ext) in OPTION_SETS {
        if *ext != "jdf" {
            continue;
        }
        let mut patches: Vec<(&str, PathBuf)> = Vec::new();
        for (tag, exe) in [("cpp", &oracle_jdiff), ("rs", &rust_jdiff)] {
            let dir = temp_dir(&format!("cross-tiny-{name}-{tag}"));
            let patch = dir.join("patch.jdf");
            let outp = run_in(&dir, exe, &jdiff_args(opts, &org, &new, &patch));
            assert_exit1(&outp, &format!("{tag} jdiff tiny/{name}"));
            patches.push((tag, patch));
        }
        for (maker, patch) in &patches {
            for (tag, exe) in [("cpp", &oracle_jdiff), ("rs", &rust_jdiff)] {
                let dir = temp_dir(&format!("cross-tiny-{name}-{maker}-by-{tag}"));
                let restored = dir.join("restored.bin");
                let outp = run_in(&dir, exe, &apply_args(&org, patch, &restored));
                assert_exit0(&outp, &format!("{tag} -u of {maker} patch tiny/{name}"));
                assert_eq!(
                    fs::read(&restored).expect("restored"),
                    TINY_NEW,
                    "{maker} patch applied by {tag} diverges for tiny/{name}"
                );
                fs::remove_dir_all(&dir).expect("clean temp dir");
            }
        }
    }
    fs::remove_dir_all(&tdir).expect("clean temp dir");
}

/// Index-table element-count equivalence (spec §18.E/§21.7): the port's
/// fixed 16-byte element divisor and the 32-bit-hkey oracle's 12 mean the
/// SAME table is requested with different MB counts (`-i 8` ≡ `-i 6`:
/// 8M/16 = 6M/12 = 524288 elements → prime 524287). With the equal table the
/// engines must agree byte-for-byte on the corpus pairs' patches.
#[test]
fn live_oracle_index_equivalence() {
    let Some(oracle) = oracle_dir() else {
        eprintln!("{}", skip_message());
        return;
    };
    for (pair, org, new) in PAIRS {
        let mut outs: Vec<(PathBuf, Output, PathBuf)> = Vec::new();
        for (tag, exe, opts) in [
            ("cpp", oracle.join("jdiff"), vec!["-i", "6"]),
            (
                "rs",
                PathBuf::from(env!("CARGO_BIN_EXE_jdiff")),
                vec!["-i", "8"],
            ),
        ] {
            let opts: Vec<&str> = opts;
            let dir = temp_dir(&format!("ieq-{pair}-{tag}"));
            let out_file = dir.join("output.bin");
            let outp = run_in(
                &dir,
                &exe,
                &jdiff_args(&opts, &fixture(org), &fixture(new), &out_file),
            );
            assert_exit1(&outp, &format!("{tag} jdiff {pair} (equal tables)"));
            assert!(
                outp.stdout.is_empty(),
                "{tag} jdiff {pair}: stdout must stay empty"
            );
            outs.push((dir, outp, out_file));
        }
        let (dir_cpp, _, file_cpp) = outs.remove(0);
        let (dir_rs, _, file_rs) = outs.remove(0);
        assert_eq!(
            fs::read(&file_rs).expect("rs output"),
            fs::read(&file_cpp).expect("cpp output"),
            "Rust (-i 8) and C++ (-i 6) diverge with equal index tables for {pair}"
        );
        fs::remove_dir_all(&dir_cpp).expect("clean temp dir");
        fs::remove_dir_all(&dir_rs).expect("clean temp dir");
    }
}

// ---------------------------------------------------------------------------
// Layer 3: round-trip gate (runs everywhere, spec §22.1)
// ---------------------------------------------------------------------------

/// `jdiff OPTS a b p && jdiff -u a p out` restores b byte-exact for every
/// pair × patch-producing option set of the §22.1 matrix (exit 1 diff — the
/// pairs differ — and exit 0 apply). The argv[0] equivalents (`jpatch`/`jptch`
/// copies) are covered in tests/roundtrip.rs.
#[test]
fn roundtrip_gate() {
    for (pair, org, new) in PAIRS {
        let new_bytes = fs::read(fixture(new)).expect("read new file");
        for (name, opts) in roundtrip_sets(pair) {
            let dir = temp_dir(&format!("rt-{pair}-{name}"));
            let patch = dir.join("patch.jdf");
            let patched = dir.join("patched.bin");
            let d = run_in(
                &dir,
                Path::new(env!("CARGO_BIN_EXE_jdiff")),
                &jdiff_args(opts, &fixture(org), &fixture(new), &patch),
            );
            assert_exit1(&d, &format!("jdiff {pair}/{name}"));
            assert!(
                fs::metadata(&patch).expect("patch file").len() > 0,
                "jdiff {pair}/{name}: patch for a differing pair must not be empty"
            );
            let p = run_in(
                &dir,
                Path::new(env!("CARGO_BIN_EXE_jdiff")),
                &apply_args(&fixture(org), &patch, &patched),
            );
            assert_exit0(&p, &format!("jdiff -u {pair}/{name}"));
            assert_eq!(
                fs::read(&patched).expect("patched output"),
                new_bytes,
                "round-trip failed for {pair}/{name}"
            );
            fs::remove_dir_all(&dir).expect("clean temp dir");
        }
    }
}

// ---------------------------------------------------------------------------
// Layer 4: francisdb cross-validation (runs everywhere, spec §16.4)
// ---------------------------------------------------------------------------

/// The third-party `jojodiff` crate (v0.1.2) applies the Rust-produced
/// patches of the NUL-free text pair. Its `patch` signature takes both
/// readers as the same concrete type (`patch<R: Read + Seek, W: Write>(
/// in_reader: &mut R, patch_reader: &mut R, out_writer: &mut W)`), so
/// `Cursor<Vec<u8>>` is used for both. Its reader defaults the operator to
/// MOD (the 0.8.5 reader semantics of spec §18.C), so the implicit-MOD
/// patches keep restoring the new files byte-exact.
#[test]
fn francisdb_cross_validation() {
    let (pair, org, new) = PAIRS[1]; // text pair, NUL-free (spec §16.4)
    let org_bytes = fs::read(fixture(org)).expect("read original file");
    let new_bytes = fs::read(fixture(new)).expect("read new file");
    for (name, opts, _) in patch_sets() {
        let dir = temp_dir(&format!("fdb-{pair}-{name}"));
        let patch = dir.join("patch.jdf");
        let d = run_in(
            &dir,
            Path::new(env!("CARGO_BIN_EXE_jdiff")),
            &jdiff_args(opts, &fixture(org), &fixture(new), &patch),
        );
        assert_exit1(&d, &format!("jdiff {pair}/{name}"));
        let patch_bytes = fs::read(&patch).expect("read patch");

        let mut org_reader = Cursor::new(org_bytes.clone());
        let mut patch_reader = Cursor::new(patch_bytes);
        let mut out: Vec<u8> = Vec::new();
        jojodiff::patch(&mut org_reader, &mut patch_reader, &mut out)
            .expect("francisdb jojodiff::patch");
        assert_eq!(
            out, new_bytes,
            "francisdb-applied patch differs for {pair}/{name}"
        );
        fs::remove_dir_all(&dir).expect("clean temp dir");
    }
}
