//! `JPatcht`: apply a patch file generated by jdiff to a source file, 1:1
//! port of C++ `src/JPatcht.cpp` (spec §18.B/§18.C).
//!
//! The input stream consists of a series of `<op> (<data> || <len>)` where
//! `<op> = <ESC> (<MOD>||<INS>||<DEL>||<EQL>||<BKT>)`, `<data> =
//! <chr>||<ESC><ESC>` and `<chr>` is any byte different from the opcodes;
//! `<ESC><ESC>` yields one `<ESC>` byte.
//!
//! 0.8.5 decoder semantics (spec §18.C): the operator defaults to MOD at the
//! start of a sequence and after `ESC <unknown>` (`JPatcht.cpp:246-254`),
//! which makes the 0.8.5 implicit-MOD wire format readable; `ESC <same-opr>`
//! inside a run is handled as data (`JPatcht.cpp:176-185`), so every
//! 0.8.1-style explicit patch (where that sequence always starts a new
//! record) is still applied exactly — one-way compatibility, §22.3. A
//! trailing lone ESC at a sequence start prints
//! `"Warning: unexpected trailing byte at end of file, patch file may be
//! corrupted.\n"` to **stderr** and returns `EXI_ERR` (`JPatcht.cpp:243`).
//! The non-LARGEFILE 64-bit-reject branch of `ufGetInt` is dead code in the
//! port (the oracle build defines `JDIFF_LARGEFILE`, §21.13).

use std::io::Write;

use crate::defs::{EOF, EXI_ERR, EXI_OK, Op, ReadType, p8, print_char};
use crate::jdebug::dbg_print;
use crate::jfile::JFile;
use crate::jfileout::JFileOut;
use crate::jout::wire::LenTier;

/// The escape wire byte (`0xA7`) as an `i32` data value: the decoder's data
/// and length arithmetic computes with C `int`s (EOF = -1 included), so the
/// escape opcode appears as a byte value wherever it rides the data channel.
const ESC_BYTE: i32 = Op::Esc as i32;

/// Patch applier (`JPatcht`, `JPatcht.h:34-114`): holds the source file, the
/// patch file, the output file and the verbosity level.
pub struct JPatcht<'a, W: Write> {
    /// Source file (`mpFilOrg`).
    fil_org: &'a mut dyn JFile,
    /// Patch file (`mpFilPch`).
    fil_pch: &'a mut dyn JFile,
    /// Output file (`mpFilOut`).
    fil_out: JFileOut<W>,
    /// Verbosity level 0, 1 or 2/3 (`miVerbse`).
    verbse: i32,
    /// Patch-file read cursor. The C++ reads the patch file with the
    /// zero-argument `JFile::get()`, i.e. `get(mzPosRed, Read)` on the
    /// file's own sequential cursor (`JFile.h:87-89`): it advances by one on
    /// every successful read and is reset to -1 on EOF/error. The Rust
    /// trait's `get` is addressed, so the applier mirrors that cursor here
    /// ([`JPatcht::pch_get`]).
    pos_pch: i64,
}

impl<'a, W: Write> JPatcht<'a, W> {
    /// Create JPatcht object (`JPatcht::JPatcht`, `JPatcht.cpp:32-38`).
    pub fn new(
        org: &'a mut dyn JFile,
        pch: &'a mut dyn JFile,
        out: JFileOut<W>,
        verbse: i32,
    ) -> Self {
        JPatcht {
            fil_org: org,
            fil_pch: pch,
            fil_out: out,
            verbse,
            pos_pch: 0,
        }
    }

    /// Returns the output file (Rust-side access to the sink for flushing;
    /// the C++ object simply goes out of scope).
    pub fn into_inner(self) -> JFileOut<W> {
        self.fil_out
    }

    /// Get one byte from the patch file at the mirrored sequential cursor
    /// (C++ zero-arg `mpFilPch.get()`, `JFile.h:87-89` = `get(mzPosRed,
    /// Read)`): the file's cursor advances by one on every successful read
    /// and is reset to -1 on EOF/error (`JFile.h:73-81`,
    /// `JFileAhead.cpp:142-147`).
    ///
    /// One patch byte or `EOF` (`JPatcht.cpp`). The decoder's length
    /// arithmetic computes with `EOF` like the C, so this is deliberately
    /// the i32 representation boundary of the typed reader.
    fn pch_get(&mut self) -> i32 {
        let li_inp = self.fil_pch.get(self.pos_pch, ReadType::Read).to_i32();
        if li_inp < 0 {
            self.pos_pch = -1;
        } else {
            self.pos_pch += 1;
        }
        li_inp
    }

    /// Get an offset from the input file (`JPatcht::ufGetInt`,
    /// `JPatcht.cpp:50-85`): length tiers `1..=252` / `253 + x` / 16-bit /
    /// 32-bit / 64-bit, big-endian; every `get` may return `EOF` (-1) and
    /// the C arithmetic computes with it (no error path).
    fn uf_get_int(&mut self) -> i64 {
        let mut li_val: i64 = i64::from(self.pch_get());

        match LenTier::from_lead(li_val) {
            /* `li_val + 1` uses the original `li_val` (EOF/-1 → 0): the C
             * arithmetic computes with the read result, no error path. */
            LenTier::L252 => li_val + 1,
            LenTier::L508 => 253 + i64::from(self.pch_get()),
            LenTier::L16 => {
                li_val = i64::from(self.pch_get());
                li_val = (li_val << 8) + i64::from(self.pch_get());
                li_val
            }
            LenTier::L32 => {
                li_val = i64::from(self.pch_get());
                li_val = (li_val << 8) + i64::from(self.pch_get());
                li_val = (li_val << 8) + i64::from(self.pch_get());
                li_val = (li_val << 8) + i64::from(self.pch_get());
                li_val
            }
            LenTier::L64 => {
                /* 64-bit form (`JDIFF_LARGEFILE`, live in the oracle build and
                 * in this port). The non-LARGEFILE branch
                 * (`fprintf(stderr, "64-bit length numbers not supported!\n");
                 * return EXI_LRG;`, `JPatcht.cpp:80-83`) is unreachable here and
                 * is ported as dead code by omission of the `#else` body
                 * (spec §21.13). */
                li_val = i64::from(self.pch_get());
                li_val = (li_val << 8) + i64::from(self.pch_get());
                li_val = (li_val << 8) + i64::from(self.pch_get());
                li_val = (li_val << 8) + i64::from(self.pch_get());
                li_val = (li_val << 8) + i64::from(self.pch_get());
                li_val = (li_val << 8) + i64::from(self.pch_get());
                li_val = (li_val << 8) + i64::from(self.pch_get());
                li_val = (li_val << 8) + i64::from(self.pch_get());
                li_val
            }
        }
    }

    /// Put one byte of output data (`JPatcht::ufPutDta`,
    /// `JPatcht.cpp:96-109`): writes the byte and — with verbosity > 1 —
    /// traces `P8zd " " P8zd " %s %02x %c\n"`. Always returns 1.
    fn uf_put_dta(
        &mut self,
        lz_pos_org: i64,
        lz_pos_out: i64,
        li_opr: Op,
        ai_dta: i32,
        az_off: i64,
    ) -> i32 {
        self.fil_out.putc(ai_dta);
        if self.verbse > 1 {
            dbg_print(format_args!(
                "{} {} {} {:02x} {}\n",
                p8(lz_pos_org + if li_opr == Op::Mod { az_off } else { 0 }),
                p8(lz_pos_out + az_off),
                if li_opr == Op::Mod { "MOD" } else { "INS" },
                ai_dta,
                print_char(ai_dta),
            ));
        }
        1
    }

    /// Read a data sequence INS or MOD (`JPatcht::ufGetDta`,
    /// `JPatcht.cpp:120-196`): outputs the pending bytes, then reads data
    /// until EOF or a new operator; `lz_mod` accumulates the offset counter.
    /// Returns the new operator, or `None` at EOF.
    fn uf_get_dta(
        &mut self,
        lz_pos_org: i64,
        lz_pos_out: i64,
        li_opr: Op,
        lz_mod: &mut i64,
        li_pnd: i32,
        li_dbl: i32,
    ) -> Option<Op> {
        let mut li_inp: i32; /* Input from mpFilPch */
        let mut li_new: i32; /* New operator */

        *lz_mod = 0;

        /* First, output the pending bytes:
           liPnd  liDbl     Output
            ESC    ESC      ESC ESC
            ESC    xxx      ESC xxx
            xxx    EOF      xxx
        (comment as in the C++; the code outputs one ESC for ESC ESC.) */
        if li_pnd != EOF {
            *lz_mod += i64::from(self.uf_put_dta(lz_pos_org, lz_pos_out, li_opr, li_pnd, *lz_mod));
            if li_pnd == ESC_BYTE && li_dbl != ESC_BYTE {
                *lz_mod +=
                    i64::from(self.uf_put_dta(lz_pos_org, lz_pos_out, li_opr, li_dbl, *lz_mod));
            }
        }

        /* Read loop */
        loop {
            li_inp = self.pch_get();
            if li_inp == EOF {
                break;
            }

            // Handle ESC-code
            if li_inp == ESC_BYTE {
                li_new = self.pch_get();
                /* `li_new as u8`: EOF (-1) truncates to 0xFF, which is not an
                 * opcode, so an EOF right after an ESC lands in the
                 * not-an-opcode arm like any unknown byte — the C++
                 * `default` arm, which outputs it as data. */
                match Op::from_byte(li_new as u8) {
                    Some(opr) if opr != Op::Esc => {
                        if opr == li_opr {
                            // <ESC> MOD within an <ESC> MOD is meaningless: handle as data
                            // <ESC> INS within an <ESC> INS is meaningless: handle as data
                            if self.verbse > 2 {
                                dbg_print(format_args!(
                                    "{} {} ESC {:02x}\n",
                                    p8(lz_pos_org + if li_opr == Op::Mod { *lz_mod } else { 0 }),
                                    p8(lz_pos_out + *lz_mod),
                                    li_new,
                                ));
                            }

                            *lz_mod += i64::from(
                                self.uf_put_dta(lz_pos_org, lz_pos_out, li_opr, li_inp, *lz_mod),
                            );
                            li_inp = li_new; // will be output below
                        } else {
                            return Some(opr);
                        }
                    }
                    Some(_) => {
                        // Double ESC: drop one
                        if self.verbse > 2 {
                            dbg_print(format_args!(
                                "{} {} ESC ESC\n",
                                p8(lz_pos_org + if li_opr == Op::Mod { *lz_mod } else { 0 }),
                                p8(lz_pos_out + *lz_mod),
                            ));
                        }

                        // Write the single ESC and continue
                        *lz_mod += i64::from(
                            self.uf_put_dta(lz_pos_org, lz_pos_out, li_opr, li_inp, *lz_mod),
                        );
                        continue;
                    }
                    None => {
                        // ESC <xxx> with <xxx> not an opcode: output as they are
                        if self.verbse > 2 {
                            dbg_print(format_args!(
                                "{} {} ESC XXX\n",
                                p8(lz_pos_org + if li_opr == Op::Mod { *lz_mod } else { 0 }),
                                p8(lz_pos_out + *lz_mod),
                            ));
                        }

                        // Write the escape, the <xxx> and continue
                        *lz_mod += i64::from(
                            self.uf_put_dta(lz_pos_org, lz_pos_out, li_opr, li_inp, *lz_mod),
                        );
                        *lz_mod += i64::from(
                            self.uf_put_dta(lz_pos_org, lz_pos_out, li_opr, li_new, *lz_mod),
                        );
                        continue;
                    }
                }
            }

            // Handle data
            *lz_mod += i64::from(self.uf_put_dta(lz_pos_org, lz_pos_out, li_opr, li_inp, *lz_mod));
        } /* while ! EOF */

        None // EOF
    }

    /// Patch function (`JPatcht::jpatch`, `JPatcht.cpp:209-338`).
    ///
    /// Returns [`EXI_OK`] on success and the raw negative `EXI_*`/length
    /// sentinels on errors (`EXI_ERR` on the trailing-ESC warning, the
    /// truncated negative lengths from `uf_get_int`, `EXI_RED`/`EXI_WRI`
    /// from the EQL copy).
    ///
    /// The C++ clears the pending-byte mirrors (`liDbl = EOF`, `liInp = EOF`,
    /// `:238-239`, `:254`, `:257-258`) in branches where nothing reads them
    /// anymore; the stores are ported as written, so the dead-store lint is
    /// silenced for this function.
    #[allow(unused_assignments)]
    pub fn jpatch(&mut self) -> i32 {
        let mut li_inp: i32; /* 1st Pending byte (EOF = no pending byte) */
        let mut li_dbl: i32 = EOF; /* 2nd Pending byte (EOF = no pending byte) */
        let mut li_opr: Option<Op>; /* Current operand (None = read next from input) */
        /* Current operand's offset. The C++ leaves `lzOff` uninitialized on
         * entry (ufGetDta sets it through the reference; DEL/EQL/BKT assign
         * before use); Rust requires an initializer, which is behaviorally
         * invisible. */
        let mut lz_off: i64 = 0;
        let mut lz_pos_org: i64 = 0; /* Position in source file */
        let mut lz_pos_out: i64 = 0; /* Position in destination file */

        li_opr = None; // no operator
        loop {
            // Read operator from input, unless this has already been done
            if li_opr.is_none() {
                li_inp = self.pch_get();
                if li_inp == EOF {
                    break;
                }

                // Handle ESC <opr>
                if li_inp == ESC_BYTE {
                    li_dbl = self.pch_get();
                    /* `li_dbl as u8`: EOF (-1) truncates to 0xFF, not an
                     * opcode, so it is classified separately below. */
                    match Op::from_byte(li_dbl as u8) {
                        Some(opr) if opr != Op::Esc => {
                            li_opr = Some(opr);
                            li_dbl = EOF;
                            li_inp = EOF;
                        } // new operator found, all ok !
                        None if li_dbl == EOF => {
                            // serious error, let's call this a trailing byte
                            eprintln!(
                                "Warning: unexpected trailing byte at end of file, \
                                 patch file may be corrupted."
                            );
                            return EXI_ERR;
                        }
                        // ESC ESC or ESC <unknown> at the start of a sequence:
                        // resolve by double pending bytes: liInp and liDbl
                        _ => {
                            li_opr = Some(Op::Mod);
                        }
                    }
                } else {
                    li_opr = Some(Op::Mod); // If an ESC <opr> is missing, set default operator (gaining two bytes)
                    li_dbl = EOF;
                }
            } else {
                li_inp = EOF; // only needed when switching between MOD and INS
                li_dbl = EOF;
            }

            // Execute the operator
            let opr = li_opr.expect("operator just read or carried over");
            match opr {
                Op::Mod => {
                    li_opr =
                        self.uf_get_dta(lz_pos_org, lz_pos_out, opr, &mut lz_off, li_inp, li_dbl);
                    if self.verbse == 1 {
                        dbg_print(format_args!(
                            "{} {} MOD {}\n",
                            p8(lz_pos_org),
                            p8(lz_pos_out),
                            lz_off
                        ));
                    }
                    lz_pos_org += lz_off;
                    lz_pos_out += lz_off;
                    if li_opr.is_none() {
                        break; // EOF: end of patch
                    }
                }

                Op::Ins => {
                    li_opr =
                        self.uf_get_dta(lz_pos_org, lz_pos_out, opr, &mut lz_off, li_inp, li_dbl);
                    if self.verbse == 1 {
                        dbg_print(format_args!(
                            "{} {} INS {}\n",
                            p8(lz_pos_org),
                            p8(lz_pos_out),
                            lz_off
                        ));
                    }
                    lz_pos_out += lz_off;
                    if li_opr.is_none() {
                        break; // EOF: end of patch
                    }
                }

                Op::Del => {
                    lz_off = self.uf_get_int();
                    if lz_off < 0 {
                        return lz_off as i32;
                    }
                    if self.verbse >= 1 {
                        dbg_print(format_args!(
                            "{} {} DEL {}\n",
                            p8(lz_pos_org),
                            p8(lz_pos_out),
                            lz_off
                        ));
                    }
                    lz_pos_org += lz_off;
                    li_opr = None; // to read next operator from input
                }

                Op::Eql => {
                    /* get length of operation */
                    lz_off = self.uf_get_int();
                    if lz_off < 0 {
                        return lz_off as i32;
                    }

                    /* show feedback */
                    if self.verbse >= 1 {
                        dbg_print(format_args!(
                            "{} {} EQL {}\n",
                            p8(lz_pos_org),
                            p8(lz_pos_out),
                            lz_off
                        ));
                    }

                    /* execute operation */
                    let li_ret = self.fil_out.copyfrom(self.fil_org, lz_pos_org, lz_off);
                    if li_ret != EXI_OK {
                        return li_ret;
                    }
                    lz_pos_org += lz_off;
                    lz_pos_out += lz_off;

                    /* Next operator */
                    li_opr = None; // to read next operator from input
                }

                Op::Bkt => {
                    lz_off = self.uf_get_int();
                    if lz_off < 0 {
                        return lz_off as i32;
                    }
                    if self.verbse >= 1 {
                        dbg_print(format_args!(
                            "{} {} BKT {}\n",
                            p8(lz_pos_org),
                            p8(lz_pos_out),
                            lz_off
                        ));
                    }
                    lz_pos_org -= lz_off;
                    li_opr = None; // to read next operator from input
                }

                /* `Esc` is the escape byte, never an operator: the
                 * read-operator branch above resolves every escape (or dies
                 * on the trailing-ESC warning). */
                Op::Esc => {}
            }
        } /* loop */

        if self.verbse >= 1 {
            dbg_print(format_args!("{} {} EOF\n", p8(lz_pos_org), p8(lz_pos_out)));
        }

        EXI_OK
    } /* jpatch */
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::defs::{EXI_ERR, EXI_OK, EXI_RED};
    use crate::jfile::JFileMem;

    /// u8 wire bytes of the opcodes (patch byte arrays are u8, the `Op`
    /// enum carries the wire values). The local definitions shadow the glob
    /// import for the test byte arrays below.
    const ESC: u8 = Op::Esc.byte();
    const MOD: u8 = Op::Mod.byte();
    const INS: u8 = Op::Ins.byte();
    const DEL: u8 = Op::Del.byte();
    const EQL: u8 = Op::Eql.byte();
    const BKT: u8 = Op::Bkt.byte();

    /// 17-byte fixture differing only in the tail (the round-trip.rs pair).
    const ORG_A: &[u8] = b"hello world hello";
    const NEW_B: &[u8] = b"hello world byebye";

    /// 0.8.5 implicit-MOD patch for (ORG_A, NEW_B): `ESC EQL 12`, MOD data
    /// "byeby" without an `ESC MOD` prefix, `ESC INS "e"`.
    const PATCH_AB: &[u8] = &[
        0xA7, 0xA3, 0x0B, // ESC EQL len=12
        b'b', b'y', b'e', b'b', b'y', // implicit MOD "byeby"
        0xA7, 0xA5, b'e', // ESC INS "e"
    ];

    /// The same patch in the 0.8.1 wire format (explicit `ESC MOD` record).
    const PATCH_AB_081: &[u8] = &[
        0xA7, 0xA3, 0x0B, // ESC EQL len=12
        0xA7, 0xA6, b'b', b'y', b'e', b'b', b'y', // ESC MOD "byeby"
        0xA7, 0xA5, b'e', // ESC INS "e"
    ];

    /// Applies `patch` to `org` at verbosity `v`; returns (rc, output).
    fn apply(org: &[u8], patch: &[u8], v: i32) -> (i32, Vec<u8>) {
        let mut org_f = JFileMem::new(org.to_vec());
        let mut pch_f = JFileMem::new(patch.to_vec());
        let out = JFileOut::new(Vec::new());
        let mut jp = JPatcht::new(&mut org_f, &mut pch_f, out, v);
        let rc = jp.jpatch();
        (rc, jp.into_inner().into_inner())
    }

    /// The 0.8.5 implicit-MOD patch (Task 18 writer output) restores the new
    /// file byte-exact: the MOD run riding the implicit operator is data.
    #[test]
    fn applies_085_implicit_mod_patch() {
        let (rc, out) = apply(ORG_A, PATCH_AB, 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out, NEW_B);
    }

    /// One-way compatibility (spec §18.C/§22.3): every 0.8.1-style explicit
    /// patch applies identically — `ESC <same-opr>` starts a new record only
    /// where the previous sequence ended, otherwise it is data.
    #[test]
    fn applies_081_explicit_mod_patch() {
        let (rc, out) = apply(ORG_A, PATCH_AB_081, 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out, NEW_B);
    }

    /// An empty patch restores nothing and succeeds (`jpatch` reads EOF at
    /// the first operator read and breaks, `JPatcht.cpp:224-226`).
    #[test]
    fn empty_patch_succeeds() {
        let (rc, out) = apply(ORG_A, &[], 0);
        assert_eq!(rc, EXI_OK);
        assert!(out.is_empty());
    }

    /// `ESC ESC` at a sequence start resolves to the default MOD operator
    /// with pending bytes (ESC, ESC): exactly one ESC is output and the rest
    /// of the sequence is MOD data (`JPatcht.cpp:246-250`, pending table
    /// `:128-139`).
    #[test]
    fn esc_esc_at_sequence_start_is_mod_data() {
        let (rc, out) = apply(b"0123456789", &[ESC, ESC, b'A', b'B'], 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out, [0xA7, b'A', b'B']);
    }

    /// `ESC <unknown>` at a sequence start also resolves to MOD and outputs
    /// both pending bytes as data (`JPatcht.cpp:246-250`).
    #[test]
    fn esc_unknown_at_sequence_start_is_mod_data() {
        let (rc, out) = apply(b"0123456789", &[ESC, b'x', b'y'], 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out, [0xA7, b'x', b'y']);
    }

    /// A plain (non-ESC) byte at a sequence start defaults the operator to
    /// MOD and is output as data (`JPatcht.cpp:252-254`); the next `ESC opr`
    /// then switches operators. (0.8.1's reader dropped such bytes.) The MOD
    /// run also advances the source position mirror, so the following EQL
    /// copies from there.
    #[test]
    fn plain_byte_at_sequence_start_is_implicit_mod_data() {
        let (rc, out) = apply(b"0123456789", &[b'X', ESC, EQL, 0x03], 0);
        assert_eq!(rc, EXI_OK);
        // 'X' as MOD data (pos_org 0 -> 1), then EQL 4 copies org[1..5].
        assert_eq!(out, b"X1234");
    }

    /// `ESC <same-opr>` inside a run is data: literal ESC followed by the
    /// operator byte (`JPatcht.cpp:176-185`).
    #[test]
    fn esc_same_opr_inside_run_is_data() {
        let (rc, out) = apply(b"0123456789", &[ESC, MOD, b'A', ESC, MOD, b'B'], 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out, [b'A', 0xA7, 0xA6, b'B']);
    }

    /// `ESC <other-opr>` inside a run switches to the new operator
    /// (`JPatcht.cpp:186-188`).
    #[test]
    fn esc_other_opr_switches_operator() {
        let (rc, out) = apply(b"0123456789", &[ESC, MOD, b'A', ESC, INS, b'B'], 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out, b"AB");
    }

    /// `ESC ESC` inside a run yields one literal ESC (`JPatcht.cpp:153-162`).
    #[test]
    fn esc_esc_inside_run_yields_one_esc() {
        let (rc, out) = apply(b"0123456789", &[ESC, MOD, b'A', ESC, ESC, b'B'], 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out, [b'A', 0xA7, b'B']);
    }

    /// DEL/EQL/BKT position arithmetic through the JFile readers: EQL copies
    /// via `copyfrom`, DEL advances the source position, BKT moves it back.
    #[test]
    fn del_eql_bkt_position_arithmetic() {
        // EQL 4 "0123", INS 'X', BKT 4, INS 'Y'.
        let patch = [
            ESC, EQL, 0x03, ESC, INS, b'X', ESC, BKT, 0x03, ESC, INS, b'Y',
        ];
        let (rc, out) = apply(b"0123456789", &patch, 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out, b"0123XY");
    }

    /// Length-tier decoding (`ufGetInt`, `JPatcht.cpp:50-85`): byte+1,
    /// `253 + x`, 16-bit, 32-bit and 64-bit big-endian forms.
    #[test]
    fn length_tiers_decode() {
        // 1-byte tier: 0x03 -> 4 bytes.
        let (rc, out) = apply(b"0123456789", &[ESC, EQL, 0x03], 0);
        assert_eq!((rc, out.as_slice()), (EXI_OK, &b"0123"[..]));

        // 2-byte tier: 252-marker, x=97 -> 253+97 = 350 bytes (org padded).
        let org = vec![0x5Au8; 400];
        let (rc, out) = apply(&org, &[ESC, EQL, 252, 97], 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out.len(), 350);

        // 16-bit tier: 253-marker, 0x0100 -> 256 bytes.
        let (rc, out) = apply(&org, &[ESC, EQL, 253, 0x01, 0x00], 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out.len(), 256);

        // 32-bit tier: 254-marker, 0x0000012C -> 300 bytes.
        let (rc, out) = apply(&org, &[ESC, EQL, 254, 0, 0, 1, 0x2C], 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out.len(), 300);

        // 64-bit tier: 255-marker, 0x000000000000012C -> 300 bytes.
        let patch = [ESC, EQL, 255, 0, 0, 0, 0, 0, 0, 1, 0x2C];
        let (rc, out) = apply(&org, &patch, 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out.len(), 300);
    }

    /// Truncated-length EOF semantics: every `getc` may return EOF (-1) and
    /// the C arithmetic computes with it (`jpatch.cpp`/`JPatcht.cpp` have no
    /// error path here).
    #[test]
    fn truncated_length_eof_arithmetic() {
        // [ESC DEL 252] at EOF: 253 + (-1) = 252 -> DEL 252, success, empty.
        let (rc, out) = apply(ORG_A, &[ESC, DEL, 252], 0);
        assert_eq!(rc, EXI_OK);
        assert!(out.is_empty());

        // First length byte at EOF: -1 < 252 -> -1 + 1 = 0 -> EQL 0.
        let (rc, out) = apply(ORG_A, &[ESC, EQL], 0);
        assert_eq!(rc, EXI_OK);
        assert!(out.is_empty());

        // 8-byte form truncated after 7 bytes: (0xFF..FF << 8) + (-1) =
        // -257 -> negative length, jpatch returns it truncated to int.
        let patch = [ESC, DEL, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF];
        let (rc, out) = apply(ORG_A, &patch, 0);
        assert_eq!(rc, -257);
        assert!(out.is_empty());
    }

    /// A lone trailing ESC at a sequence start is a serious error: the
    /// warning line goes to stderr and `EXI_ERR` is returned
    /// (`JPatcht.cpp:241-245`). (The line itself is pinned byte-exact by the
    /// child-process test in tests/roundtrip.rs.)
    #[test]
    fn trailing_esc_at_sequence_start_is_exi_err() {
        let (rc, out) = apply(ORG_A, &[ESC], 0);
        assert_eq!(rc, EXI_ERR);
        assert!(out.is_empty());
    }

    /// A trailing ESC *after* data is not a sequence start: the default arm
    /// of `ufGetDta` outputs the ESC and the operand getc's EOF (-1) becomes
    /// byte 0xFF (`JPatcht.cpp:164-174`); no warning, success.
    #[test]
    fn trailing_esc_after_data_appends_esc_and_ff() {
        let (rc, out) = apply(b"0123456789", &[ESC, MOD, b'x', ESC], 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out, [b'x', 0xA7, 0xFF]);
    }

    /// An EQL copy running past the source end fails the fallback byte-loop
    /// read with `EXI_RED` (via `JFileOut::copyfrom`).
    #[test]
    fn eql_past_source_end_is_exi_red() {
        let (rc, out) = apply(ORG_A, &[ESC, EQL, 99], 0); // len 100 > 17
        assert_eq!(rc, EXI_RED);
        assert_eq!(out, ORG_A); // everything readable was copied first
    }

    /// The single-EQL patch of an identical pair restores the whole file
    /// (17 bytes -> `ESC EQL 16`).
    #[test]
    fn identical_pair_single_eql_restores() {
        let (rc, out) = apply(ORG_A, &[ESC, EQL, 0x10], 0);
        assert_eq!(rc, EXI_OK);
        assert_eq!(out, ORG_A);
    }

    /// A BKT seek before the start of the source only moves the position
    /// mirror; 0.8.5 has no seek check (`jpatch.cpp`'s exit-6 path is gone)
    /// and the failure surfaces lazily in the next EQL copy's read:
    /// `copyfrom`'s fallback loop gets EOF at the negative position and
    /// reports a short read (`EXI_RED`).
    #[test]
    fn bkt_before_start_succeeds_until_next_copy() {
        // BKT 4 alone: position -4 is never read, plain success.
        let (rc, out) = apply(b"0123456789", &[ESC, BKT, 0x03], 0);
        assert_eq!(rc, EXI_OK);
        assert!(out.is_empty());

        // BKT 4 followed by EQL 4: the copy reads at -4 -> EXI_RED.
        let patch = [ESC, BKT, 0x03, ESC, EQL, 0x03];
        let (rc, out) = apply(b"0123456789", &patch, 0);
        assert_eq!(rc, EXI_RED);
        assert!(out.is_empty());
    }

    // -- verbose traces (byte-exact formats at `JPatcht.cpp:101-107` for the
    //    per-byte lines, `:156-158/:166-169/:179-182` for the ESC traces,
    //    `:265-335` for the op summaries and the EOF line) go to stddbg —
    //    the process debug stream, which an in-process unit test cannot
    //    capture. Their gating and exact bytes are pinned by the
    //    child-process tests in tests/roundtrip.rs (the test harness
    //    re-execs itself with --exact).
}
